### ISSUE TITLE
issue logging in after connecting

### ISSUE THREAD

**Issue by duke-arioch** [Maxopoly/Angelia-core#2]
issues logging into servers - do they need certain server-side support?

when i log into vanilla mc 1.12.2 server on localhost with the 1.0.02 core i get:

```
[08:59:15 INFO]: Beginning login to localhost
[08:59:15 ERROR]: Could not connect to server
java.io.IOException: Received invalid packet with id 1 while waiting for login success
        at com.github.maxopoly.angeliacore.connection.login.GameJoinHandler.parseLoginSuccess(GameJoinHandler.java:29) ~[Angelia-Cmd.jar:?]
        at com.github.maxopoly.angeliacore.connection.ServerConnection.connect(ServerConnection.java:179) ~[Angelia-Cmd.jar:?]
        at com.github.maxopoly.angeliacore.connection.ActiveConnectionManager.initConnection(ActiveConnectionManager.java:27) [Angelia-Cmd.jar:?]
        at com.github.maxopoly.angelia_cmd.Main.main(Main.java:23) [Angelia-Cmd.jar:?]
```

when i try to connect to civ classics i get:

```
[09:03:10 INFO]: No access tokens were loaded from save file as safe file didn't exist
[09:03:11 INFO]: Successfully authenticated ***** with UUID *****
[09:03:11 INFO]: Initializing connection process for account ***** to mc.civclassic.com:25565
[09:03:11 INFO]: Connected socket to mc.civclassic.com
[09:03:11 INFO]: Requesting protocol version from mc.civclassic.com
[09:03:11 INFO]: mc.civclassic.com is on version Spigot 1.12.2 with protocol 340
[09:03:11 INFO]: Sending handshake to mc.civclassic.com
[09:03:11 INFO]: Beginning login to mc.civclassic.com
[09:03:11 INFO]: Parsing encryption request from mc.civclassic.com
[09:03:11 INFO]: Authenticating connection attempt to mc.civclassic.com against Yggdrassil session server
[09:03:12 INFO]: Sending encryption reply to mc.civclassic.com
[09:03:12 INFO]: Enabling sync encryption with mc.civclassic.com
[09:03:12 INFO]: Enabling compression with 256 as compression threshhold for connection to mc.civclassic.com
[09:03:12 INFO]: Received login success package for player ******** with UUID ********************
[09:03:12 INFO]: Switching connection to play state
[09:03:12 INFO]: Registering plugin DiggingBot
[09:03:12 INFO]: Registering plugin dummy
[09:03:12 INFO]: Registering plugin IronBot
[09:03:12 INFO]: Registering plugin ObbyBot
[09:03:12 INFO]: Registering plugin TunnelBot
[09:03:12 INFO]: Registering plugin MelonBot
[09:03:12 INFO]: Registering plugin TreeBot
[09:03:12 INFO]: Registering plugin SnitchBot
[09:03:12 INFO]: Loaded a total of 8 plugin(s)
[09:03:12 INFO]: Disconnected from mc.civclassic.com due to timeout
[09:03:12 INFO]: Closing socket with mc.civclassic.com
```
in the first case do i need to do something else?I looked on http://wiki.vg/Protocol#Clientbound_4 and found:

Packet ID | State | Bound To 
-- | -- | -- 
0x01 | Login | Client

Field Name | Field Type | Notes
-- | -- | --
Server ID | String (20) | Appears to be empty
Public Key Length | VarInt | Length of Public Key
Public Key | Byte Array |  
Verify Token Length | VarInt | Length of Verify Token. Always 4 for Notchian servers.
Verify Token | Byte Array | A sequence of random bytes generated by the server

are they the same issue and do i need to do something differently?

**Comment by Maxopoly** [comment]
You are unable to connect to the vanilla server, because it is local host. Localhost works differently protocol wise and not properly supported yet.

**Comment by Maxopoly** [comment]
Fixed by https://github.com/Maxopoly/Angelia-core/commit/d5d75b92d03f91b9158f0cc35ac60498c4d492e8

**Comment by duke-arioch** [comment]
thanks Max - rebased mine on the latest. changed local host to my ip address (worked) and then connected to civ classics - working great!
