### ISSUE TITLE
error

### ISSUE THREAD

**Issue by okx-code** [Maxopoly/Angelia-core#7]
fix

```
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.github.maxopoly.angeliacore.event.EventBroadcaster.broadcast(EventBroadcaster.java:45) [angelia.jar:?]
        at com.github.maxopoly.angeliacore.connection.play.packets.in.ChatMessagePacketHandler.handlePacket(ChatMessagePacketHandler.java:21) [angelia.jar:?]
        at com.github.maxopoly.angeliacore.connection.play.Heartbeat.processPacket(Heartbeat.java:87) [angelia.jar:?]
        at com.github.maxopoly.angeliacore.connection.play.Heartbeat.run(Heartbeat.java:168) [angelia.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
        at java.util.TimerThread.run(Timer.java:506) [?:?]
Caused by: org.json.JSONException: JSONObject["value"] not a string.
        at org.json.JSONObject.getString(JSONObject.java:721) ~[angelia.jar:?]
        at com.github.maxopoly.angeliacore.model.chat.ChatComponentParser.parseHoverEvent(ChatComponentParser.java:183) ~[angelia.jar:?]
        at com.github.maxopoly.angeliacore.model.chat.ChatComponentParser.parseChatComponentInternal(ChatComponentParser.java:70) ~[angelia.jar:?]
        at com.github.maxopoly.angeliacore.model.chat.ChatComponentParser.parseChatComponent(ChatComponentParser.java:43) ~[angelia.jar:?]
        at com.github.maxopoly.angeliacore.event.events.ChatMessageReceivedEvent.getParsedChat(ChatMessageReceivedEvent.java:45) ~[angelia.jar:?]
```

**Comment by masecla22** [comment]
Could you offer some more information about how you created this error?

**Comment by Maxopoly** [comment]
Could you add a debug thing to provide the message which caused this?
